version: '3.8'

services:
  # Application
  app:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
      args: 
        - APP_ENV=${APP_ENV}
        - PHP_VERSION=${PHP_VERSION}
        - REMOTE_WORKING_DIR=${REMOTE_WORKING_DIR}
    working_dir: ${REMOTE_WORKING_DIR}
    volumes:
      - ${LOCAL_WORKING_DIR}:${REMOTE_WORKING_DIR}
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/my-xdebug.ini
    depends_on:
      - "database"
    ports:
      - "9000:9000"
    networks:
      - laravel
  # Web Server
  web:
    build:
      context: .
      dockerfile: ./docker/web.dockerfile
    working_dir: ${REMOTE_WORKING_DIR}
    volumes:
      - ${LOCAL_WORKING_DIR}:${REMOTE_WORKING_DIR}
    depends_on:
      - "app"
    ports:
      - 8081:80
    hostname: web.local
    networks:
      laravel:    
        aliases:
          - web.local
    restart: always
  # Database
  database:
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - 33061:3306
  # Database management
  pma:
    image: phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_PORT=${DB_PORT}
    depends_on:
      - database
    ports:
        - 8888:80
  # Mailing Server
  mailhog:
    image: mailhog/mailhog:latest
    logging:
      driver: 'none'
    ports:
      - 1025:1025 
      - 8025:8025 

volumes:
  dbdata:

networks:
  laravel: